name: Run Cypress Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        node-version: [ 22.x ] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        browser: [ chrome, firefox ]
        containers: [1, 2] # Uses 2 parallel instances

    steps:
      # 1. Code Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Running Cypress tests
      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --record \
            --key 9f264146-cc33-40ca-b436-a2841eeaf9a8 \
            --parallel \
            --group "browser-${{ matrix.browser }}" \
            --browser ${{ matrix.browser }} 

      # 5. Upload results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/
